"""empty message

Revision ID: 389fc1d74747
Revises: 92ad705068b2
Create Date: 2020-10-22 20:49:16.990729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389fc1d74747'
down_revision = '92ad705068b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('in_deuce', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('serve_gap', sa.Integer(), nullable=True))
    op.drop_column('user', 'point_gap')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('point_gap', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'serve_gap')
    op.drop_column('game', 'in_deuce')
    # ### end Alembic commands ###
