"""empty message

Revision ID: 625fa0832233
Revises: d8e7f5937807
Create Date: 2020-10-22 14:52:20.364142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625fa0832233'
down_revision = 'd8e7f5937807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('game_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'game_complete')
    # ### end Alembic commands ###
