"""empty message

Revision ID: 92ad705068b2
Revises: 625fa0832233
Create Date: 2020-10-22 14:57:07.859484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ad705068b2'
down_revision = '625fa0832233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('point_gap', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'point_gap')
    # ### end Alembic commands ###
