"""empty message

Revision ID: 95f76979849e
Revises: 3bdfab2b97f9
Create Date: 2020-10-22 13:00:04.373905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95f76979849e'
down_revision = '3bdfab2b97f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('score_sum', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'score_sum')
    # ### end Alembic commands ###
