"""empty message

Revision ID: 96d9030c0621
Revises: 97c7f4082a7c
Create Date: 2020-10-22 12:34:14.914124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d9030c0621'
down_revision = '97c7f4082a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('current_serving', sa.String(length=32), nullable=True),
    sa.Column('winner', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('game_score', sa.Column('game_id', sa.String(length=32), nullable=False))
    op.create_foreign_key(None, 'game_score', 'game', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_score', type_='foreignkey')
    op.drop_column('game_score', 'game_id')
    op.drop_table('game')
    # ### end Alembic commands ###
