"""empty message

Revision ID: b35a2d18de87
Revises: 95f76979849e
Create Date: 2020-10-22 13:48:07.479926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35a2d18de87'
down_revision = '95f76979849e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('current_round', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'current_round')
    # ### end Alembic commands ###
