"""empty message

Revision ID: d8e7f5937807
Revises: b35a2d18de87
Create Date: 2020-10-22 14:23:40.317216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e7f5937807'
down_revision = 'b35a2d18de87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_score', sa.Column('game_round', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_score', 'game_round')
    # ### end Alembic commands ###
